### ISSUE TITLE
Correct wording of readme

### ISSUE THREAD

**Issue by alerque** [sylr/yage#9]
> `yage` is a fork

No it's not. It may have started life that way, but according to the code I see and the rest of the readme after this misleading line, `yage` is not a fork. It's stand alone project that uses the `age` library and extends the CLI with YAML data handling options. It may function as an alternative CLI, but it's not a fork. If you call it a fork people are going to worry about data compatibility, security, etc.

Mind you I like this arrangement — I would even go farther and remove the rest of the compatibility for us as a general purpose CLI and focus exclusively on the embedded YAML handling — I just think you should call it what it is.

**Comment by sylr** [comment]
Hi,

I disagree with you. I think `yage` is clearly a fork, but maybe not the one think of.

The README says it well, it's a fork of `filippo.io/age/cmd/age` which is the [go package](https://github.com/FiloSottile/age/tree/master/cmd/age) which builds the `age` binary, and not a fork of `filippo.io/age`, which is the library containing the cryptographic logic.

The second line of the README is also pretty explicit according to me:

> This project contains no cryptographic logic, all of that remains in the original project.

`yage` may be a standalone project for now, but since the majority of its codebase has been taken from `age`, I think it's only normal to credit the original author(s) by labeling this a fork.
